registration, login, account opening test suite, Transfer funds test suite, loan request test suite

diff --git a/.github/workflows/User_registration_test_suite.yml b/.github/workflows/User_registration_test_suite.yml
--- a/.github/workflows/User_registration_test_suite.yml
+++ b/.github/workflows/User_registration_test_suite.yml
@@ -180,3 +180,182 @@ jobs:
                         esac
                       sleep 10
                     done
+
+
+
+      - name: Run Transfer Funds test suite
+        run: |
+                  echo "Triggering TestRigor tests..."
+
+
+
+                                      curl -X POST \
+                    -H 'Content-type: application/json' \
+                    -H 'auth-token: 37b7140f-1cc9-4e89-919b-992b32b3d9fe' \
+                    --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+                    https://api.testrigor.com/api/v1/apps/raPitYPKjFtfTHCA2/retest
+
+                  sleep 10
+
+                  while true
+                  do
+                    echo " "
+                    echo "==================================="
+                    echo " Checking run status"
+                    echo "==================================="
+                    response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/raPitYPKjFtfTHCA2/status' -H 'auth-token: 37b7140f-1cc9-4e89-919b-992b32b3d9fe' -H 'Accept: application/json')
+                    code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+                    body=$(echo "$response" | sed -n '/{/,/}/p')
+                    echo "Status code: " $code
+                    echo "Response: " $body
+                    case $code in
+                      4*|5*)
+                        # 400 or 500 errors
+                        echo "Error calling API"
+                        exit 1
+                        ;;
+                      200)
+                        # 200: successfully finished
+                        echo "Test finished successfully"
+                        exit 0
+                        ;;
+                      227|228)
+                        # 227: New - 228: In progress
+                        echo "Test is not finished yet"
+                        ;;
+                      229)
+                        # 229: Canceled
+                        echo "Test canceled"
+                        exit 1
+                        ;;
+                      230)
+                        # 230: Failed
+                        echo "Test finished but failed"
+                        exit 1
+                        ;;
+                      *)
+                        echo "Unknown status"
+                        exit 1
+                      esac
+                    sleep 10
+                  done
+
+
+      - name: Run Transfer Funds test suite
+        run: |
+                  echo "Triggering TestRigor tests..."
+
+
+
+
+
+                                      curl -X POST \
+                    -H 'Content-type: application/json' \
+                    -H 'auth-token: b11f60f6-82b5-453f-9422-a55d74e0d013' \
+                    --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+                    https://api.testrigor.com/api/v1/apps/tAH7c9kofBL3sADue/retest
+
+                  sleep 10
+
+                  while true
+                  do
+                    echo " "
+                    echo "==================================="
+                    echo " Checking run status"
+                    echo "==================================="
+                    response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/tAH7c9kofBL3sADue/status' -H 'auth-token: b11f60f6-82b5-453f-9422-a55d74e0d013' -H 'Accept: application/json')
+                    code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+                    body=$(echo "$response" | sed -n '/{/,/}/p')
+                    echo "Status code: " $code
+                    echo "Response: " $body
+                    case $code in
+                      4*|5*)
+                        # 400 or 500 errors
+                        echo "Error calling API"
+                        exit 1
+                        ;;
+                      200)
+                        # 200: successfully finished
+                        echo "Test finished successfully"
+                        exit 0
+                        ;;
+                      227|228)
+                        # 227: New - 228: In progress
+                        echo "Test is not finished yet"
+                        ;;
+                      229)
+                        # 229: Canceled
+                        echo "Test canceled"
+                        exit 1
+                        ;;
+                      230)
+                        # 230: Failed
+                        echo "Test finished but failed"
+                        exit 1
+                        ;;
+                      *)
+                        echo "Unknown status"
+                        exit 1
+                      esac
+                    sleep 10
+                  done
+
+
+
+      - name: Run Transfer Funds test suite
+        run: |
+                  echo "Triggering TestRigor tests..."
+
+
+
+
+                          curl -X POST \
+                    -H 'Content-type: application/json' \
+                    -H 'auth-token: 2e1076d8-69a2-479f-8ee9-218e6cbd305f' \
+                    --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+                    https://api.testrigor.com/api/v1/apps/ppAQmiFMGDoG3u7fb/retest
+
+                  sleep 10
+
+                  while true
+                  do
+                    echo " "
+                    echo "==================================="
+                    echo " Checking run status"
+                    echo "==================================="
+                    response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/ppAQmiFMGDoG3u7fb/status' -H 'auth-token: 2e1076d8-69a2-479f-8ee9-218e6cbd305f' -H 'Accept: application/json')
+                    code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+                    body=$(echo "$response" | sed -n '/{/,/}/p')
+                    echo "Status code: " $code
+                    echo "Response: " $body
+                    case $code in
+                      4*|5*)
+                        # 400 or 500 errors
+                        echo "Error calling API"
+                        exit 1
+                        ;;
+                      200)
+                        # 200: successfully finished
+                        echo "Test finished successfully"
+                        exit 0
+                        ;;
+                      227|228)
+                        # 227: New - 228: In progress
+                        echo "Test is not finished yet"
+                        ;;
+                      229)
+                        # 229: Canceled
+                        echo "Test canceled"
+                        exit 1
+                        ;;
+                      230)
+                        # 230: Failed
+                        echo "Test finished but failed"
+                        exit 1
+                        ;;
+                      *)
+                        echo "Unknown status"
+                        exit 1
+                      esac
+                    sleep 10
+                  done
