registration, login and account opening test suite

diff --git a/.github/workflows/User_registration_test_suite.yml b/.github/workflows/User_registration_test_suite.yml
--- a/.github/workflows/User_registration_test_suite.yml
+++ b/.github/workflows/User_registration_test_suite.yml
@@ -123,3 +123,60 @@ jobs:
                       esac
                     sleep 10
                   done
+
+
+      - name: Run Account Opening test suite
+        run: |
+                  echo "Triggering TestRigor tests..."
+
+
+                                      curl -X POST \
+                      -H 'Content-type: application/json' \
+                      -H 'auth-token: 513115e3-7819-492b-adf1-558316dfe04d' \
+                      --data '{"forceCancelPreviousTesting":true,"storedValues":{"storedValueName1":"Value"}}' \
+                      https://api.testrigor.com/api/v1/apps/rdMhsGj2niDpZ2Lh9/retest
+
+                    sleep 10
+
+                    while true
+                    do
+                      echo " "
+                      echo "==================================="
+                      echo " Checking run status"
+                      echo "==================================="
+                      response=$(curl -i -o - -s -X GET 'https://api.testrigor.com/api/v1/apps/rdMhsGj2niDpZ2Lh9/status' -H 'auth-token: 513115e3-7819-492b-adf1-558316dfe04d' -H 'Accept: application/json')
+                      code=$(echo "$response" | grep HTTP |  awk '{print $2}')
+                      body=$(echo "$response" | sed -n '/{/,/}/p')
+                      echo "Status code: " $code
+                      echo "Response: " $body
+                      case $code in
+                        4*|5*)
+                          # 400 or 500 errors
+                          echo "Error calling API"
+                          exit 1
+                          ;;
+                        200)
+                          # 200: successfully finished
+                          echo "Test finished successfully"
+                          exit 0
+                          ;;
+                        227|228)
+                          # 227: New - 228: In progress
+                          echo "Test is not finished yet"
+                          ;;
+                        229)
+                          # 229: Canceled
+                          echo "Test canceled"
+                          exit 1
+                          ;;
+                        230)
+                          # 230: Failed
+                          echo "Test finished but failed"
+                          exit 1
+                          ;;
+                        *)
+                          echo "Unknown status"
+                          exit 1
+                        esac
+                      sleep 10
+                    done
